import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '@/components/Navbar/Navbar'
import PrayerTime from '@/components/PrayerTime/PrayerTime'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Jida clock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={`${styles.main} ${inter.className}`}>

        {/* div with red border */}
        <div className='w-[100%] mx-auto'>
          <PrayerTime />

        </div>

      </main>
    </>
  )
}
